Update

diff --git a/.bin/google-adc b/.bin/google-adc
--- a/.bin/google-adc
+++ b/.bin/google-adc
@@ -1,8 +1,9 @@
 #!/usr/bin/env bash
 
-test -z "$GOOGLE_APPLICATION_CREDENTIALS" && (
-  echo "Missing environment variable GOOGLE_APPLICATION_CREDENTIALS" >&2; exit 1
-)
+if test -z "$GOOGLE_APPLICATION_CREDENTIALS"; then
+  echo "Missing environment variable GOOGLE_APPLICATION_CREDENTIALS" >&2
+  exit 1
+fi
 
 gcloud auth application-default login \
 && mv ~/.config/gcloud/application_default_credentials.json $GOOGLE_APPLICATION_CREDENTIALS
